src/objects/LabTools_Job__c.object
<CustomObject>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastRunOn__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Runner__c</fullName>
        <label>Runner</label>
        <referenceTo>LabTools_Runner__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LabTools_Runner__c.object
<CustomObject>
    <fields>
        <fullName>LastRunOn__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NextRunOn__c</fullName>
        <label>Next Run On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RecurrenceRate__c</fullName>
        <label>Recurrence Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurrenceType__c</fullName>
        <label>RecurrenceType</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartOn__c</fullName>
        <label>Start On</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Runner</label>
    <nameField>
        <label>Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Runners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LabTools_JobRunner.cls
global class LabTools_JobRunner implements LabTools_ISchedulable {

	global void execute() {

		if (now == null) now = DateTime.now();
		List<LabTools_Runner__c> runners = repository.Echo([
			SELECT Name, RecurrenceType__c, RecurrenceRate__c, (SELECT Name, Enabled__c FROM Jobs__r)
			FROM LabTools_Runner__c
			WHERE StartOn__c <= :now
				AND (NextRunOn__c = NULL OR NextRunOn__c <= :now)
			ORDER BY NextRunOn__c DESC
			LIMIT 5
		]);

		for(LabTools_Runner__c runner : runners) {

			DateTime next;
			if (runner.RecurrenceType__c == 'Hours') {
				next = now.addHours((Integer)runner.RecurrenceRate__c);
			} else if (runner.RecurrenceType__c == 'Days') {
				next = now.addDays((Integer)runner.RecurrenceRate__c);
			} else if (runner.RecurrenceType__c == 'Months') {
				next = now.addMonths((Integer)runner.RecurrenceRate__c);
			} else if (runner.RecurrenceType__c == 'Years') {
				next = now.addYears((Integer)runner.RecurrenceRate__c);
			}

			runner.LastRunOn__c = now;
			runner.NextRunOn__c = next;

			for(LabTools_Job__c job : runner.Jobs__r) {
				if (job.Enabled__c == false) continue;
				Database.executebatch(new LabTools_JobWrapper(job.Name));
			}

		}

		repository.Modify(runners);
	}



	global LabTools_JobRunner() {
		repository = new LabTools_Repository();
	}

	@TestVisible private LabTools_JobRunner(LabTools_IRepository r, DateTime n)
	{
		repository = r;
		now = n;
	}



	private LabTools_IRepository repository;
	private DateTime now;

}