src/objects/LabTools_Job__c.object
<CustomObject>
    <fields>
        <fullName>Runner__c</fullName>
        <label>Runner</label>
        <referenceTo>LabTools_Runner__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LabTools_Runner__c.object
<CustomObject>
    <fields>
        <fullName>NextRunOn__c</fullName>
        <label>Next Run On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RecurrenceRate__c</fullName>
        <label>Recurrence Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecurrenceType__c</fullName>
        <label>RecurrenceType</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartOn__c</fullName>
        <label>Start On</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Runner</label>
    <nameField>
        <label>Runner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Runners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LabTools_JobRunner_Tests.cls
@isTest
private class LabTools_JobRunner_Tests {

	@isTest static void WhenHours_ShouldSetNextRunInHours() {
		TestRepo repo = new TestRepo('Hours', 2);
		Datetime now = Datetime.now();
		LabTools_JobRunner jRunner = new LabTools_JobRunner(repo, now);

		Test.startTest();
		jRunner.execute();
		Test.stopTest();

		System.assertEquals(1, repo.EchoCalled);
		System.assertEquals(1, repo.ModifyCalled);
		System.assertEquals(1, repo.Modified.size());
		System.assertEquals(now.addHours(2), ((LabTools_Runner__c)repo.Modified[0]).NextRunOn__c);
	}


	@isTest static void WhenDays_ShouldSetNextRunInDays() {
		TestRepo repo = new TestRepo('Days', 3);
		Datetime now = Datetime.now();
		LabTools_JobRunner jRunner = new LabTools_JobRunner(repo, now);

		Test.startTest();
		jRunner.execute();
		Test.stopTest();

		System.assertEquals(1, repo.EchoCalled);
		System.assertEquals(1, repo.ModifyCalled);
		System.assertEquals(1, repo.Modified.size());
		System.assertEquals(now.addDays(3), ((LabTools_Runner__c)repo.Modified[0]).NextRunOn__c);
	}


	@isTest static void WhenMonths_ShouldSetNextRunInMonths() {
		TestRepo repo = new TestRepo('Months', 4);
		Datetime now = Datetime.now();
		LabTools_JobRunner jRunner = new LabTools_JobRunner(repo, now);

		Test.startTest();
		jRunner.execute();
		Test.stopTest();

		System.assertEquals(1, repo.EchoCalled);
		System.assertEquals(1, repo.ModifyCalled);
		System.assertEquals(1, repo.Modified.size());
		System.assertEquals(now.addMonths(4), ((LabTools_Runner__c)repo.Modified[0]).NextRunOn__c);
	}


	@isTest static void WhenYears_ShouldSetNextRunInYears() {
		TestRepo repo = new TestRepo('Years', 5);
		Datetime now = Datetime.now();
		LabTools_JobRunner jRunner = new LabTools_JobRunner(repo, now);

		Test.startTest();
		jRunner.execute();
		Test.stopTest();

		System.assertEquals(1, repo.EchoCalled);
		System.assertEquals(1, repo.ModifyCalled);
		System.assertEquals(1, repo.Modified.size());
		System.assertEquals(now.addYears(5), ((LabTools_Runner__c)repo.Modified[0]).NextRunOn__c);
	}


	@isTest static void WhenIntegrating_ShouldNotFailRun() {
		LabTools_Runner__c runner = new LabTools_Runner__c(
			Name = 'Test',
			RecurrenceRate__c = 1,
			RecurrenceType__c = 'Hours',
			StartOn__c = Datetime.now()
		);
		insert runner;

		List<LabTools_Job__c> testJobs = new List<LabTools_Job__c>();
		testJobs.add(new LabTools_Job__c(
			Name = LabTools_HeartbeatJob.class.getName(),
			Runner__c = runner.Id
		));
		insert testJobs;

		LabTools_JobRunner jRunner = new LabTools_JobRunner();

		Test.startTest();
		jRunner.execute();
		Test.stopTest();
	}




	private class TestRepo extends LabTools_RepositoryTestStub {

		public Integer EchoCalled = 0;
		public override List<SObject> Echo(List<SObject> values) {
			EchoCalled++;
			return new List<LabTools_Runner__c> {
				new LabTools_Runner__c(
					RecurrenceType__c = recurrenceType,
					RecurrenceRate__c = recurrenceRate
				)
			};
		}

		public Integer ModifyCalled = 0;
		public List<SObject> Modified;
		public override void Modify(List<SObject> values) {
			ModifyCalled++;
			Modified = values;
		}


		public TestRepo(String t, Decimal r) {
			recurrenceType = t;
			recurrenceRate = r;
		}

		private String recurrenceType;
		private Decimal recurrenceRate;
	}

}