src/objects/LabTools_ConfigVar__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Config Var</label>
    <nameField>
        <label>Config Var Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Config Vars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LabTools_ConfigVars.cls
global class LabTools_ConfigVars implements LabTools_IConfigVars {

	global String Read(String key) {
		List<LabTools_ConfigVar__c> results = [
			SELECT Value__c
			FROM LabTools_ConfigVar__c
			WHERE Name = :key
		];

		if (results.size() == 0) return null;

		return results[0].Value__c;
	}

	global Map<String, String> ReadAll(List<String> keys) {
		List<LabTools_ConfigVar__c> values = [
			SELECT Name, Value__c
			FROM LabTools_ConfigVar__c
			WHERE Name = :keys
		];

		Map<String, String> result = new Map<String, String>();
		for(LabTools_ConfigVar__c var : values) {
			result.put(var.Name, var.Value__c);
		}

		return result;
	}

}